blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/kdcllc/AI-Driven-FastApi-Template/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/kdcllc/AI-Driven-FastApi-Template/blob/master/README.md
    about: Check out our comprehensive documentation
